use cartas;
CREATE TABLE RAREZA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    RAREZA VARCHAR(100)
);

CREATE TABLE CARTAS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PODER INT NOT NULL,
    VELOCIDAD INT NOT NULL,
    ID_RAREZA INT NOT NULL,
    FOREIGN KEY (ID_RAREZA) REFERENCES RAREZA(ID)
		ON UPDATE CASCADE
);

INSERT INTO RAREZA (RAREZA) VALUES
('comun'), ('poco comun'), ('rara'), ('muy rara'), ('epica'), ('legendaria'), ('mitica'), ('se');

INSERT INTO CARTAS(NOMBRE, PODER, VELOCIDAD, ID_RAREZA) 
VALUES ('mago', 80, 20, 2),  ('orco', 50, 50, 1), ('pan', 100, 1, 8), ('elfo', 75, 70, 5);

